Repository hmcts/civil-sdt-commissioning, pull requests merged in 2023-09, with the labels that each got.

#56 Temporarily suppressed CVE-2023-41080
  config/owasp/suppressions.xml
Labels: ns:civil, prd:civil, rel:civil-sdt-commissioning-pr-56

#55 SDT-160: Update renovate configuration
  .github/renovate.json
Labels: ns:civil, prd:civil, rel:civil-sdt-commissioning-pr-55

#65 Update gradle to version 7.6.2
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
Labels: ns:civil, prd:civil, rel:civil-sdt-commissioning-pr-65

#66 Fix CVE-2023-41080
  .gitignore
  build.gradle
  config/owasp/suppressions.xml
Labels: ns:civil, prd:civil, rel:civil-sdt-commissioning-pr-66

#82 Temporarily suppress jetty CVEs
  config/owasp/suppressions.xml
Labels: ns:civil, prd:civil, rel:civil-sdt-commissioning-pr-82

#83 SDT-166: SDT common version updated to 1.1.0
  build.gradle
Labels: ns:civil, prd:civil, rel:civil-sdt-commissioning-pr-83
