Repository hmcts/civil-sdt-commissioning, pull requests merged in 2023-06, with the labels that each got.

#40 Temporarily suppressed CVE-2023-20883
  config/owasp/suppressions.xml
Labels: ns:civil, prd:civil, rel:civil-sdt-commissioning-pr-40

#41 Fix CVE-2023-20883
  build.gradle
  config/owasp/suppressions.xml
Labels: ns:civil, prd:civil, rel:civil-sdt-commissioning-pr-41

#43 Reduce AppInsights health sampling rate
  lib/applicationinsights.json
Labels: ns:civil, prd:civil, rel:civil-sdt-commissioning-pr-43

#45 Temporarily suppress CVE-2023-35116
  config/owasp/suppressions.xml
Labels: ns:civil, prd:civil, rel:civil-sdt-commissioning-pr-45

#44 SDT-129: CxfConfig added to sdt commissioning
  build.gradle
  producers-commissioning/.springBeans
  producers-commissioning/src/end-to-end-test/java/uk/gov/moj/sdt/producers/comx/RequestBulkFeedbackTest.java
  producers-commissioning/src/end-to-end-test/java/uk/gov/moj/sdt/producers/comx/SubmitBulkTest.java
  producers-commissioning/src/end-to-end-test/java/uk/gov/moj/sdt/producers/comx/SubmitQueryTest.java
  producers-commissioning/src/main/java/uk/gov/moj/sdt/producers/comx/config/CxfConfig.java
  producers-commissioning/src/main/java/uk/gov/moj/sdt/producers/comx/sdtws/SdtEndpointPortType.java
  src/main/java/uk/gov/moj/sdt/interceptors/service/PersistServiceRequestImpl.java
Labels: ns:civil, prd:civil, rel:civil-sdt-commissioning-pr-44
