Repository hmcts/civil-sdt-commissioning, pull requests merged in 2023-05, with the labels that each got.

#23 Fix build issues in main branch
  .github/workflows/codeql.yml
  infrastructure/main.tf
  src/functionalTest/java/uk/gov/hmcts/reform/sdt/controllers/SampleFunctionalTest.java
  src/functionalTest/resources/application-functional-test.yaml
  src/main/java/uk/gov/hmcts/reform/sdt/Application.java
Labels: ns:civil, prd:civil, no-changes, rel:civil-sdt-commissioning-pr-23

#27 Fix build issues in main branch
  Jenkinsfile_CNP
  docker-compose.yml
Labels: ns:civil, prd:civil, rel:civil-sdt-commissioning-pr-27

#30 Fix build issues
  Jenkinsfile_CNP
  Jenkinsfile_nightly
  build.gradle
Labels: ns:civil, prd:civil, rel:civil-sdt-commissioning-pr-30

#31 Remove Security Scan from nightly pipeline
  Jenkinsfile_nightly
Labels: ns:civil, prd:civil, rel:civil-sdt-commissioning-pr-31

#32 DTSPO-13810 reschedule jenkins nightly builds
  Jenkinsfile_nightly
Labels: ns:civil, prd:civil, rel:civil-sdt-commissioning-pr-32

#34 DTSPO-13810 reschedule nightlybuilds to start at 8am
  Jenkinsfile_nightly
Labels: ns:civil, prd:civil, rel:civil-sdt-commissioning-pr-34

#33 Configure project to use Application Insights v3
  Dockerfile
  charts/civil-sdt-commissioning/Chart.yaml
  charts/civil-sdt-commissioning/values.yaml
  lib/applicationinsights.json
  src/main/resources/application.yaml
Labels: ns:civil, prd:civil, rel:civil-sdt-commissioning-pr-33
