Repository hmcts/civil-sdt-commissioning, pull requests merged in 2023-12, with the labels that each got.

#133 Temporarily suppress CVE-2023-46589
  config/owasp/suppressions.xml
Labels: ns:civil, prd:civil, rel:civil-sdt-commissioning-pr-133

#139 SDT-182 resolving CVE-2023-6378 and CVE-2023-6481
  build.gradle
  config/owasp/suppressions.xml
Labels: ns:civil, prd:civil, rel:civil-sdt-commissioning-pr-139

#141 Update tomcatVersion to v9.0.84
  build.gradle
Labels: ns:civil, prd:civil, rel:civil-sdt-commissioning-pr-141
