Repository hmcts/civil-sdt-commissioning, pull requests merged in 2024-10, with the labels that each got.

#265 Updated tomcat to version 9.0.96
  build.gradle
Labels: ns:civil, prd:civil, rel:civil-sdt-commissioning-pr-265

#267 Updating phase-3 branch with changes made to master
  Dockerfile
  build.gradle
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
Labels: ns:civil, prd:civil, rel:civil-sdt-commissioning-pr-267

#272 SDT-203: Added new CMC errors
  build.gradle
  producers-commissioning/src/main/java/uk/gov/moj/sdt/producers/comx/config/bulkfeedback/BulkFeedbackConfigAOne.java
  producers-commissioning/src/main/java/uk/gov/moj/sdt/producers/comx/config/bulkfeedback/BulkFeedbackConfigBOne.java
  producers-commissioning/src/main/java/uk/gov/moj/sdt/producers/comx/config/bulkfeedback/BulkFeedbackConfigBTwo.java
  producers-commissioning/src/main/java/uk/gov/moj/sdt/producers/comx/config/bulkfeedback/BulkFeedbackConfigBase.java
  producers-commissioning/src/main/java/uk/gov/moj/sdt/producers/comx/config/bulkfeedback/BulkFeedbackConfigCOne.java
  producers-commissioning/src/main/java/uk/gov/moj/sdt/producers/comx/dao/MockIndividualRequestDao.java
  producers-commissioning/src/main/java/uk/gov/moj/sdt/producers/comx/services/MockCmcFeedbackService.java
  producers-commissioning/src/unit-test/java/uk/gov/moj/sdt/producers/comx/config/bulkfeedback/BulkFeedbackConfigBOneTest.java
  producers-commissioning/src/unit-test/java/uk/gov/moj/sdt/producers/comx/config/bulkfeedback/BulkFeedbackConfigBTwoTest.java
  producers-commissioning/src/unit-test/java/uk/gov/moj/sdt/producers/comx/config/bulkfeedback/BulkFeedbackConfigCOneTest.java
  producers-commissioning/src/unit-test/java/uk/gov/moj/sdt/producers/comx/services/MockCmcFeedbackServiceTest.java
Labels: ns:civil, prd:civil, rel:civil-sdt-commissioning-pr-272
